name: Weather Update v3

on:
  schedule:
    # - cron: '0 */6 * * *'  # Run every 6 hours
    - cron: '*/2 * * * *'  # Run every 2 minutes

jobs:
  update_weather:
    runs-on: ubuntu-latest

    env:
      TZ: "Asia/Tbilisi"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies

    - name: Run Python script
      run: python get_weather.py
      env:
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}

    - name: Generate HTML file
      run: python generate_html.py

    - name: Commit and push changes
      run: |
        git config --global user.name "Wezer-Man"
        git config --global user.email "lperto@gmail.com"
        git add weather_data.csv index.html
        git commit -m "Update weather data and HTML - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
